services:
  db:
    image: postgres:13
    container_name: superset_db
    restart: always
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - superset_network

  redis:
    image: redis:7
    container_name: superset_redis
    restart: always
    networks:
      - superset_network

  superset:
    image: apache/superset:latest
    container_name: superset_app
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "3000:8088"
    volumes:
      - ./superset:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    environment:
      SUPERSET_SECRET_KEY: your_secret_key
      SQLALCHEMY_DATABASE_URI: postgresql://superset:superset@db:5432/superset
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FLASK_APP: superset
      PYTHONPATH: /app/pythonpath:/app/superset_home
      ENABLE_PROXY_FIX: "true"
      TALISMAN_ENABLED: "false"
      SUPERSET_WEBSERVER_TIMEOUT: 300
      SUPERSET_FEATURE_FLAGS: '{"EMBEDDED_SUPERSET":true,"DASHBOARD_RBAC":false,"DASHBOARD_NATIVE_FILTERS":true,"VERSIONED_EXPORT":true,"GLOBAL_ASYNC_QUERIES":true,"DASHBOARD_NATIVE_FILTERS_SET":true,"DASHBOARD_FILTERS_EXPERIMENTAL":true,"ALLOW_DASHBOARD_EMBEDDING":true}'
      SUPERSET_DOMAIN: "http://localhost:3000"
      ENABLE_CORS: "true"
      CORS_OPTIONS: '{"supports_credentials":true,"allow_origins":["*"],"allow_methods":["GET","POST"],"allow_headers":["*"]}'
      WTF_CSRF_ENABLED: "false"
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_WEBSERVER_ADDRESS: "0.0.0.0"
    networks:
      - superset_network
    command: >
      bash -c "pip install -U pip &&
              pip install psycopg2-binary redis uwsgi &&
              superset db upgrade &&
              superset fab create-admin
                --username admin
                --firstname Superset
                --lastname Admin
                --email admin@superset.com
                --password admin &&
              superset init &&
              uwsgi --http 0.0.0.0:8088 
                    --module superset.app:create_app() 
                    --master 
                    --processes 2 
                    --threads 2 
                    --http-keepalive 
                    --http-auto-chunked 
                    --http-chunked-input 
                    --need-app"

networks:
  superset_network:
    driver: bridge

volumes:
  postgres_data: